### ISSUE TITLE
Polygon deploy // Web3js for decrypt & watch

### ISSUE THREAD

**Issue by maximedotair** [nomasters/killcord#16]
Hey ! Very great project !

It is possible to deploy this on polygon ? 

Do you think it's possible to use a web3js interface for watcher user / decrypter ? 

And my last question : When user watch/decrypt the smart contract or the publisher use gas ? We need to check that the both have ethereum ? 

Thanks :)

**Comment by maximedotair** [comment]
I have this error when i want to deploy on polygon (i have the polygon subscription on my infura account) but : 

Failed to deploy new killcord contract: only replay-protected (EIP-155) transactions allowed over RPC

Thanks :)

**Comment by n2p5** [comment]
I'll have to look into this. I'm not super familiar with polygon stuff, so I'll poke around and see what I can find. the Killcord CLI tool defaults to an INFURA account I had for it to make it easy to try stuff out, so it might be that it has some restrictions. 
If you are running an ETH endpoint on localhost, you can point to that instead of INFURA with the ENVs

```
KILLCORD_PAYLOAD_RPCURL      # this is for IPFS
KILLCORD_CONTRACT_RPCURL   # this is for ETH
```
