### ISSUE TITLE
it was my understanding that secrets cannot be stored on ethereum?

### ISSUE THREAD

**Issue by thinkloop** [nomasters/killcord#4]
Very cool project, thanks for putting it together.

It was my understanding that secrets cannot be safely stored in ethereum - is this not true?

**Comment by n2p5** [comment]
@thinkloop - I know there are proposals out there to store secrets, but killcord side steps this by keeping the decryption key "off chain" in the killcord owner config file and in the publisher. Once killcord _does_ publish the key, it is clear text and open to the world by design.

**Comment by thinkloop** [comment]
If I understand correctly:

- encrypted payload stored on ipfs
- key to unlock payload stored locally in plain text
- on detonation, local publisher broadcasts key on ethereum for public consumption 

?

**Comment by n2p5** [comment]
@thinkloop  Yep, this is early POC, so I side step local system opSec for the time being. I've got a couple of ideas bouncing around about encrypting the local config with a user-defined passphrase so that the decryption key never lives in plain text, but that will be a future implementation.

The publisher can run with a lighter version of the config and it can run on any trusted system. The idea was that you could(should) run multiple publishers for resiliency and run them anywhere from AWS Lambda in multiple regions, a raspberry pi, your local machine, whatever you trust to hold your secret key

**Comment by thinkloop** [comment]
Makes sense, it is a tough problem to solve, at some point some key somewhere has to be accessible without the creator of the key being available (not sure how a passphrase could work).

With regards to the last step, why involve ethereum instead of publishing on ipfs as well?

**Comment by n2p5** [comment]
@thinkloop solid question. You could absolutely write it to IPFS, but everything in IPFS is immutable and undeletable, so you'd still need to announce the generated endpoint hash to another service that could respond to an API request. For Killcord, I'm just using ethereum as a highly available append-only key/value store with open `get` requests and restricted `put`s (only the owner and publisher accounts have access to writing, and the publisher can only write a decryption key). 

You can check out the code here, if you are interested:
https://github.com/nomasters/killcord/blob/master/contract/killcord.sol

The initial version of `killcord` was for "public disclosures", but I've been working on a new `provider` system so that "private disclosures" and alternate backends and storage can be used. I should have a primitive structure for this in the next release. I haven't added new providers, but I've moved ethereum code into an ethereum provider, ipfs code into an ipfs provider and local system interaction into a local provider. I like the structure its bringing and hope it opens up cool implementation possibilities like using S3, keybase, Google Drive, and more.
